# Generated by Django 3.2.16 on 2024-12-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='Категория поста', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='\tместоположение'),
        ),
    ]
